pipeline:
  identifier: Build_MERN_Stack_Example_1683541798525
  name: Build MERN-Stack-Example
  orgIdentifier: default
  projectIdentifier: The_Very_First_project
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
